Repository quixio/quix-streams, pull requests merged in 2024-12, with the labels that each got.

#653 Source: files (s3 and local)
  docs/build/build.py
  docs/connectors/sources/file-source.md
  docs/connectors/sources/local-file-source.md
  docs/connectors/sources/s3-file-source.md
  quixstreams/sources/community/file/__init__.py
  quixstreams/sources/community/file/compressions/base.py
  quixstreams/sources/community/file/compressions/gzip.py
  quixstreams/sources/community/file/file.py
  quixstreams/sources/community/file/formats/base.py
  quixstreams/sources/community/file/origins/__init__.py
  quixstreams/sources/community/file/origins/base.py
  quixstreams/sources/community/file/origins/local.py
  quixstreams/sources/community/file/origins/s3.py
Labels: connector

#669 Source: Azure Origin for FileSource
  conda/meta.yaml
  docs/build/build.py
  docs/connectors/sources/microsoft-azure-file-source.md
  pyproject.toml
  quixstreams/sources/community/file/origins/__init__.py
  quixstreams/sources/community/file/origins/azure.py
Labels: connector

#686 Re-raise the exceptions from the platform API
  quixstreams/platforms/quix/config.py
Labels: bug

#677 fix broken doc refs
  docs/connectors/sources/amazon-s3-source.md
  docs/connectors/sources/local-file-source.md
  docs/connectors/sources/microsoft-azure-file-source.md
Labels: documentation

#691 BigQuery Sink: fix bug around dataset and table ids
  quixstreams/sinks/community/bigquery.py
Labels: connector

#675 Cleanup Examples and Tutorials
  docs/build/README.md
  docs/connectors/sources/custom-sources.md
  docs/introduction.md
  docs/tutorials/README.md
  docs/tutorials/anomaly-detection/application.py
  docs/tutorials/anomaly-detection/tutorial.md
  docs/tutorials/anomaly-detection/tutorial_app.py
  docs/tutorials/purchase-filtering/application.py
  docs/tutorials/purchase-filtering/producer.py
  docs/tutorials/purchase-filtering/tutorial.md
  docs/tutorials/purchase-filtering/tutorial_app.py
  docs/tutorials/websocket-source/requirements.txt
  docs/tutorials/websocket-source/tutorial.md
  docs/tutorials/websocket-source/tutorial_app.py
  docs/tutorials/word-count/application.py
  docs/tutorials/word-count/producer.py
  docs/tutorials/word-count/tutorial.md
  docs/tutorials/word-count/tutorial_app.py
  examples/.gitignore
  examples/README.md
  examples/__init__.py
  examples/bank_example/README.md
  examples/bank_example/__init__.py
  examples/bank_example/json_version/__init__.py
  examples/bank_example/json_version/consumer.py
  examples/bank_example/json_version/producer.py
  examples/bank_example/quix_platform_version/__init__.py
  examples/bank_example/quix_platform_version/consumer.py
  examples/bank_example/quix_platform_version/producer.py
  examples/bank_example/quix_platform_version/quix_vars.env
  examples/custom_websocket_source/README.md
  examples/custom_websocket_source/__init__.py
  examples/docker-compose.yml
  examples/env_vars.env
  examples/requirements.txt
  mkdocs.yml
Labels: documentation
