Repository quixio/quix-streams, pull requests merged in 2024-09, with the labels that each got.

#420 Feature: Sources API
  quixstreams/app.py
  quixstreams/dataframe/dataframe.py
  quixstreams/logging.py
  quixstreams/models/topics/manager.py
  quixstreams/models/topics/topic.py
  quixstreams/sources/__init__.py
  quixstreams/sources/base.py
  quixstreams/sources/manager.py
  quixstreams/sources/multiprocessing.py
  tests/test_quixstreams/test_app.py
  tests/test_quixstreams/test_checkpointing.py
  tests/test_quixstreams/test_sources/__init__.py
  tests/test_quixstreams/test_sources/test_manager.py
  tests/utils.py
Labels: enhancement

#482 Add Conda configuration
  conda/README.md
  conda/meta.yaml
  conda/post-link.sh
Labels: enhancement

#501 Fix typo in FixedTimeWindowDefinition.reduce docstring
  quixstreams/dataframe/windows/definitions.py
Labels: documentation

#448 Kafka Replicator Source & Quix Environment Source
  docs/build/build.py
  docs/connectors/sources/README.md
  docs/connectors/sources/kafka-source.md
  docs/connectors/sources/quix-source.md
  mkdocs.yml
  quixstreams/app.py
  quixstreams/checkpointing/__init__.py
  quixstreams/checkpointing/checkpoint.py
  quixstreams/models/topics/admin.py
  quixstreams/rowproducer.py
  quixstreams/sources/__init__.py
  quixstreams/sources/kafka/__init__.py
  quixstreams/sources/kafka/checkpoint.py
  quixstreams/sources/kafka/kafka.py
  quixstreams/sources/kafka/quix.py
  tests/conftest.py
  tests/test_quixstreams/fixtures.py
  tests/test_quixstreams/test_app.py
  tests/test_quixstreams/test_models/test_topics/test_topics.py
  tests/test_quixstreams/test_sources/test_kafka.py
Labels: enhancement

#505 Add an example of custom websocket source
  examples/custom_websocket_source/README.md
  examples/custom_websocket_source/__init__.py
  examples/custom_websocket_source/main.py
  examples/custom_websocket_source/requirements.txt
Labels: documentation

#493 Script to test Conda build
  conda/README.md
  conda/test.sh
Labels: code-quality

#522 Downgrade confluent-kafka to 2.4.0
  conda/meta.yaml
  requirements.txt
Labels: bug

#480 additional doc updates for branching
  docs/advanced/branching.md
  docs/advanced/consuming-multiple-topics.md
  docs/advanced/dataframe-assignments.md
  docs/processing.md
  mkdocs.yml
Labels: documentation
