Repository quixio/quix-streams, pull requests merged in 2025-01, with the labels that each got.

#670 Source: background file downloads for FileSource
  quixstreams/sources/community/file/file.py
Labels: connector

#689 Influxdb3 Sink: add some functionality and QoL improvements
  quixstreams/sinks/core/influxdb3.py
Labels: connector

#688 Feature: Collection Aggregations
  docs/windowing.md
  quixstreams/dataframe/windows/definitions.py
  quixstreams/dataframe/windows/sliding.py
  quixstreams/dataframe/windows/time_based.py
  quixstreams/state/base/transaction.py
  quixstreams/state/metadata.py
  quixstreams/state/rocksdb/windowed/metadata.py
  quixstreams/state/rocksdb/windowed/partition.py
  quixstreams/state/rocksdb/windowed/serialization.py
  quixstreams/state/rocksdb/windowed/state.py
  quixstreams/state/rocksdb/windowed/transaction.py
  quixstreams/state/types.py
  tests/test_quixstreams/test_dataframe/test_windows/test_hopping.py
  tests/test_quixstreams/test_dataframe/test_windows/test_sliding.py
  tests/test_quixstreams/test_dataframe/test_windows/test_tumbling.py
  tests/test_quixstreams/test_state/test_partition.py
  tests/test_quixstreams/test_state/test_rocksdb/test_windowed/test_partition.py
  tests/test_quixstreams/test_state/test_rocksdb/test_windowed/test_serialization.py
  tests/test_quixstreams/test_state/test_rocksdb/test_windowed/test_state.py
  tests/test_quixstreams/test_state/test_rocksdb/test_windowed/test_transaction.py
Labels: enhancement

#728 Do not process late message in sliding windows
  quixstreams/dataframe/windows/sliding.py
  tests/test_quixstreams/test_dataframe/test_windows/test_sliding.py
Labels: bug
